# Generated by Django 6.0.3 on 2026-03-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='current_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
