# Generated by Django 6.0.3 on 2026-03-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides_app', '0002_ride_current_location_ride_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='current_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='current_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
